- name: creating ssh keys id_rsa (for jenkins)
  hosts: jenkins
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:

    - name: Create SSH key for user jenkins 
      ansible.builtin.user:
        name: jenkins
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_bits: 2048
        ssh_key_file: /home/jenkins/.ssh/id_ed25519

    - name: fetch pub keys to local
      fetch:
        src: "/home/jenkins/.ssh/id_rsa.pub"
        dest: "/mnt/d/home/esm/B11-5/.metadata/01-pub-{{ inventory_hostname }}"
        flat: true

    - name: fetch private keys to local
      fetch:
        src: "/home/jenkins/.ssh/id_rsa"
        dest: "/mnt/d/home/esm/B11-5/.metadata/01-priv-{{ inventory_hostname }}"
        flat: true

- name: exchange ssh keys id_rsa (for jenkins)
  hosts: nodes
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:
    - name: export public ssh-key to prod and stating
      authorized_key:
        user: jenkins
        state: present
        key: "{{ lookup('file', '/mnt/d/home/esm/B11-5/.metadata/ed-pub-158.160.47.185') }}"

    - name: set correct permisions on authorized_key
      file:
        path: "/home/jenkins/.ssh/authorized_keys"
        owner: jenkins
        group: jenkins
        mode: "0644"