- name: install docker and config users
  hosts: a
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  roles:
    - role: "/mnt/d/home/esm/B11-5/ansible/roles/docker"

- name: add user jenkins to docker group
  hosts: nodes
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  roles:
    - role: "/mnt/d/home/esm/B11-5/ansible/roles/ssh-keys"