- name: jenkins
  hosts: hosts
  gather_facts: false
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:
  
    - name: install epel
      yum:
        name: epel-release
        update_cache: true

    - name: install docker
      yum:
        name: docker

    - name: start docker service
      service:
        name: docker
        state: started

    - name: run jenkins container
      shell:
        cmd: "docker run --name jenkins -p 8080:8080 -p 50000:50000 -v /mnt/d/home/esm/B11-5/jenkins/home jenkins/jenkins"